apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-argocd-endpoint
spec:
  package: "ghcr.io/krateoplatformops/provider-argocd-endpoint:VERSION"
  packagePullPolicy: IfNotPresent
