apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  namespace: crossplane-system
  name: provider-github
spec:
  package: "ghcr.io/krateoplatformops/provider-github:VERSION"
  packagePullPolicy: Always
